{
    "name": "ModoOps Core",
    "summary": "Plataforma ModoOps — Liquid Glass v2, hubs Mostrador/Depósito/Compras/Fiscal",
    "description": """
Módulo base de ModoOps (evolución de modoops Core): assets SCSS,
personalización POS y backend Odoo 19, hubs KPI cards composables.
Template clonable para nuevos proyectos ModoOps — renombrar y adaptar por vertical.
    """,
    "author": "ModoOps",
    "website": "https://modoops.com",
    "category": "ModoOps",
    "version": "19.0.1.0.1",
    "license": "LGPL-3",
    "depends": [
        "base",
        "base_setup",
        "web",
        "mail",
        "product",
        "point_of_sale",
        "pos_discount",
        "stock",
        "sale_management",
        "purchase",
        "account",
        "l10n_ar",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/modoops_groups.xml",
        "views/mo_price_list_import_views.xml",
        "views/mo_workshop_views.xml",
        "views/product_template_views.xml",
        "report/mo_modoops_layout.xml",
        "report/mo_work_order_report.xml",
        "report/mo_report_document_inherits.xml",
        "data/mail_template_mo_work_order.xml",
        "data/modoops_fiscal_config.xml",
        "data/hub_inventory_data.xml",
        "data/hub_sales_data.xml",
        "data/hub_sales_labels_update.xml",
        "data/hub_purchase_data.xml",
        "data/hub_accounting_data.xml",
        "data/hub_accounting_customers_hide.xml",
        "data/hub_workshop_data.xml",
        "data/launcher_tiles_data.xml",
        "data/hide_native_apps.xml",
        "views/launcher_menus.xml",
        "views/modoops_app_menu.xml",
        "views/hub_menus.xml",
        "views/login_templates.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            (
                "before",
                "web/static/src/scss/base_frontend.scss",
                "modoops_core/static/src/scss/modoops_tokens.scss",
            ),
            "modoops_core/static/src/scss/modoops_login.scss",
        ],
        "web.assets_backend": [
            (
                "before",
                "web/static/src/scss/bootstrap_overridden.scss",
                "modoops_core/static/src/scss/modoops_tokens.scss",
            ),
            "modoops_core/static/src/scss/modoops_backend.scss",
            "modoops_core/static/src/scss/modoops_rail.scss",
            "modoops_core/static/src/scss/modoops_list.scss",
            "modoops_core/static/src/scss/modoops_launcher.scss",
            "modoops_core/static/src/scss/modoops_hub.scss",
            "modoops_core/static/src/scss/modoops_onboarding_smoke.scss",
            "modoops_core/static/src/js/services/mo_title_service.js",
            "modoops_core/static/src/js/services/mo_hub_service.js",
            "modoops_core/static/src/js/services/mo_pos_entry.js",
            "modoops_core/static/src/js/services/mo_pos_theme.js",
            "modoops_core/static/src/js/services/mo_onboarding_full_catalog.js",
            "modoops_core/static/src/js/services/mo_onboarding_tour.js",
            "modoops_core/static/src/js/services/mo_onboarding_chrome.js",
            "modoops_core/static/src/js/services/mo_onboarding_persist.js",
            "modoops_core/static/src/js/services/mo_onboarding_host.js",
            "modoops_core/static/src/js/services/mo_onboarding_smoke.js",
            "modoops_core/static/src/js/services/mo_shell_path.js",
            "modoops_core/static/src/js/services/mo_onboarding_smoke_boot.js",
            "modoops_core/static/src/js/services/mo_onboarding_smoke_service.js",
            "modoops_core/static/src/js/services/mo_onboarding_host_boot.js",
            "modoops_core/static/src/js/services/mo_onboarding_host_service.js",
            "modoops_core/static/src/js/launcher/mo_launcher_service.js",
            "modoops_core/static/src/js/chrome/mo_rail_context.js",
            "modoops_core/static/src/js/services/mo_rail_service.js",
            "modoops_core/static/src/js/services/mo_nav_user_service.js",
            "modoops_core/static/src/js/launcher/mo_launcher_tile.xml",
            "modoops_core/static/src/js/launcher/mo_launcher_tile.js",
            "modoops_core/static/src/js/launcher/mo_launcher_shell.xml",
            "modoops_core/static/src/js/launcher/mo_launcher_shell.js",
            "modoops_core/static/src/js/hubs/mo_hub_section_body.xml",
            "modoops_core/static/src/js/hubs/mo_hub_section_body.js",
            "modoops_core/static/src/js/hubs/mo_app_hub.xml",
            "modoops_core/static/src/js/hubs/mo_app_hub.js",
            "modoops_core/static/src/js/components/mo_entry_card.xml",
            "modoops_core/static/src/js/components/mo_entry_card.js",
            "modoops_core/static/src/js/components/mo_section_rail.xml",
            "modoops_core/static/src/js/components/mo_section_rail.js",
            "modoops_core/static/src/js/hubs/inventory_hub.xml",
            "modoops_core/static/src/js/hubs/inventory_hub.js",
            "modoops_core/static/src/js/hubs/inventory_hub_action.js",
            "modoops_core/static/src/js/hubs/sales_hub.xml",
            "modoops_core/static/src/js/hubs/sales_hub.js",
            "modoops_core/static/src/js/hubs/sales_hub_action.js",
            "modoops_core/static/src/js/hubs/purchase_hub.xml",
            "modoops_core/static/src/js/hubs/purchase_hub.js",
            "modoops_core/static/src/js/hubs/purchase_hub_action.js",
            "modoops_core/static/src/js/hubs/accounting_hub.xml",
            "modoops_core/static/src/js/hubs/accounting_hub.js",
            "modoops_core/static/src/js/hubs/accounting_hub_action.js",
            "modoops_core/static/src/js/hubs/workshop_hub.xml",
            "modoops_core/static/src/js/hubs/workshop_hub.js",
            "modoops_core/static/src/js/hubs/workshop_hub_action.js",
            "modoops_core/static/src/js/launcher/app_launcher.xml",
            "modoops_core/static/src/js/launcher/app_launcher.js",
            "modoops_core/static/src/js/chrome/mo_rail_nav.xml",
            "modoops_core/static/src/js/chrome/mo_rail_nav.js",
            "modoops_core/static/src/js/chrome/mo_mobile_bottom_bar.xml",
            "modoops_core/static/src/js/chrome/mo_mobile_bottom_bar.js",
            "modoops_core/static/src/js/chrome/mo_webclient_patch.xml",
            "modoops_core/static/src/js/chrome/mo_webclient_patch.js",
        ],
        "point_of_sale._assets_pos": [
            "modoops_core/static/src/scss/modoops_tokens.scss",
            "modoops_core/static/src/scss/modoops_pos.scss",
            "modoops_core/static/src/scss/modoops_onboarding_smoke.scss",
            "modoops_core/static/src/js/services/mo_pos_theme.js",
            "modoops_core/static/src/js/services/mo_pos_order_discount.js",
            "modoops_core/static/src/js/pos/mo_product_screen_order_discount.js",
            "modoops_core/static/src/js/services/mo_onboarding_tour.js",
            "modoops_core/static/src/js/services/mo_onboarding_chrome.js",
            "modoops_core/static/src/js/services/mo_onboarding_smoke.js",
            "modoops_core/static/src/js/services/mo_shell_path.js",
            "modoops_core/static/src/js/services/mo_onboarding_smoke_boot.js",
            "modoops_core/static/src/js/services/mo_onboarding_smoke_pos.js",
        ],
        "web._assets_primary_variables": [
            (
                "after",
                "web/static/src/webclient/navbar/navbar.variables.scss",
                "modoops_core/static/src/scss/modoops_primary_variables.scss",
            ),
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
}
